import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // HealthHack PRIS-Inspired Palette
        "hh-bg": "#041a1d",
        "hh-surface": "#0f3c3f",
        "hh-surface-raised": "#1e4e51",
        "hh-border": "#246a6d",
        "hh-text": "#f5f6f6",
        "hh-text-muted": "#c2d3d4",
        "hh-cyan": "#63d2e5",
        "hh-mint": "#30d6bc",
        "hh-emerald": "#2ac298",
        "hh-highlight": "#7dfbf2",
        "hh-action": "#ff6a00", // PRIS Orange for conversion
        "hh-time": "#ca9b52", // PRIS Gold for time milestones

        // Backward compatibility
        background: "#041a1d",
        surface: "#0f3c3f",
        "surface-dim": "#041a1d",
        "surface-bright": "#1e4e51",
        "surface-container-lowest": "#031011",
        "surface-container-low": "#0f3c3f",
        "surface-container": "#1e4e51",
        "surface-container-high": "#246a6d",
        "surface-container-highest": "#2e5d60",
        "on-surface": "#f5f6f6",
        "on-surface-variant": "#c2d3d4",
        "inverse-surface": "#f5f6f6",
        "inverse-on-surface": "#041a1d",
        outline: "#246a6d",
        "outline-variant": "#1e4e51",
        "surface-tint": "#63d2e5",
        primary: "#ffffff",
        "on-primary": "#041a1d",
        "primary-container": "#30d6bc",
        "on-primary-container": "#041a1d",
        "inverse-primary": "#2ac298",
        secondary: "#63d2e5",
        "on-secondary": "#041a1d",
        "secondary-container": "#1e4e51",
        "on-secondary-container": "#c2d3d4",
        tertiary: "#ff6a00",
        "on-tertiary": "#041a1d",
        "tertiary-container": "#ca9b52",
        "on-tertiary-container": "#041a1d",
        error: "#ff8a7a",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#7dfbf2",
        "primary-fixed-dim": "#63d2e5",
        "on-primary-fixed": "#041a1d",
        "on-primary-fixed-variant": "#0f3c3f",
        "secondary-fixed": "#63d2e5",
        "secondary-fixed-dim": "#30d6bc",
        "on-secondary-fixed": "#041a1d",
        "on-secondary-fixed-variant": "#1e4e51",
        "tertiary-fixed": "#ff6a00",
        "tertiary-fixed-dim": "#ca9b52",
        "on-tertiary-fixed": "#041a1d",
        "on-tertiary-fixed-variant": "#0f3c3f",
        "surface-variant": "#1e4e51",
        "surface-low": "#0f3c3f",
        "neon-cyan": "#63d2e5",
      },
      fontFamily: {
        sora: ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        hanken: ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        thai: ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        mono: ["var(--font-space-mono)", "Space Mono", "monospace"],
        "display-lg": ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        "headline-lg": ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        "headline-md": ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        "headline-lg-mobile": ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        "body-lg": ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        "body-md": ["var(--font-noto-sans-thai)", "Noto Sans Thai", "sans-serif"],
        "data-mono": ["var(--font-space-mono)", "Space Mono", "monospace"],
        "label-caps": ["var(--font-space-mono)", "Space Mono", "monospace"],
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
